---
apiVersion: v2
name: filebrowser
version: 2.0.1
kubeVersion: ">=1.16.0-0"
description: filebrowser provides a file managing interface within a specified directory
type: application
keywords:
  - filebrowser
home: https://github.com/mikevader/charts/tree/master/charts/stable/filebrowser
sources:
  - https://github.com/filebrowser/filebrowser
dependencies:
  - name: common
    repository: https://mikevader.github.io/charts
    version: 4.6.0
maintainers:
  - name: mikevader
    email: mikevader@users.noreply.github.com
icon: https://raw.githubusercontent.com/filebrowser/logo/master/icon.png

# renovate: image=filebrowser/filebrowser
appVersion: v2.52.0

annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: Fixes a bug where the config files is mounted incorrectly
