---
apiVersion: v2
name: radarr
version: 16.5.7
kubeVersion: ">=1.16.0-0"
description: A fork of Sonarr to work with movies Ã  la Couchpotato
type: application
keywords:
  - radarr
  - torrent
  - usenet
home: https://github.com/mikevader/charts/tree/master/charts/stable/radarr
sources:
  - https://github.com/Radarr/Radarr
  - https://github.com/mikevader/container-images/
dependencies:
  - name: common
    repository: https://mikevader.github.io/charts
    version: 4.6.0
maintainers:
  - name: mikevader
    email: mikevader@users.noreply.github.com
icon: https://github.com/Radarr/Radarr/blob/aphrodite/Logo/512.png?raw=true

# renovate: image=ghcr.io/mikevader/radarr
appVersion: v6.0.4.10291

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.6.0
